name: memento
description: Memento
dependencies:
    polymer: '>=0.10.0-pre.7 <0.11.0'
    browser: '>=0.10.0 <1.0.0'
    js: any
    route_hierarchical: '>=0.4.17 <1.0.0' 
    bootjack: any
    bot: ">=0.26.2 <0.27.0"
    bot_web: '>=0.21.0'
    bot_test: '>=0.1.5'
    csslib: '>=0.9.0 <0.10.0'
    hop: '>=0.28.3+2'
    bot_test: '>=0.1.5'
    csslib: '>=0.9.0 <0.10.0'
    hop: '>=0.28.3+2'
    html5lib: '>=0.9.1 <0.10.0'
    unittest: '>=0.9.0 <0.10.0'
transformers:
- polymer:
    entry_points: web/index.html
    



