name: Thesis
description: A sample Polymer application
dependencies:
    polymer:  '>=0.9.5'
    browser: any
    js: any
    route_hierarchical: '>=0.4.17 <1.0.0'
transformers:
- polymer:
    entry_points: web/index.html
