name: memento
description: Memento
dependencies:
    polymer: '>=0.10.0-pre.7 <0.11.0'
    browser: '>=0.10.0 <1.0.0'
    js: any
    bot: any
    route_hierarchical: '>=0.4.17 <1.0.0' 
    bootjack: any
    angular: any
transformers:
- polymer:
    entry_points: web/index.html
    



